dems@task-ib:~$ cat database/compose.yaml
services:
  db:
    image: postgres:15.8
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dems
      - POSTGRES_PASSWORD=Oumousabana
      - POSTGRES_DB=portfolio
    volumes:
      - pg_data_task:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  pg_data_task: