# Generated by Django 5.1.1 on 2024-09-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dems", "0005_alter_user_adresse"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="option",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
