# Generated by Django 5.1.1 on 2024-11-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dems", "0010_imageproject_remove_project_demo_alter_project_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
