# Generated by Django 5.1.1 on 2024-12-02 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dems", "0011_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
        migrations.AddField(
            model_name="imageproject",
            name="project",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="dems.project"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="image_first",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
    ]
