# Generated by Django 5.1.1 on 2024-12-02 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dems", "0014_remove_comment_name_remove_testimonial_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonial",
            name="email",
        ),
        migrations.AlterField(
            model_name="comment",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_project",
                to="dems.project",
            ),
        ),
    ]
